version: '3.8'
services:
  api:
    container_name: bandanize-api
    restart: unless-stopped
    build:
      context: ./api
    ports:
      - '8080:8080'

  ui:
    container_name: bandanize-ui
    restart: unless-stopped
    build:
      context: ./ui
    ports:
      - '3000:3000'

  database:
    container_name: bandanize-db
    image: mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db

volumes:
  dbdata: