FROM node:20

LABEL org.opencontainers.image.source = "https://github.com/r-dvl/bandanize"

# Setup
ENV REACT_APP_API_URL=http://localhost:8080
WORKDIR /bandanize/ui

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy code
COPY . .

# App listener port
EXPOSE 8081

CMD ["npm", "start"]