FROM python:3.10-alpine

WORKDIR /api

COPY ./requirements.txt /api/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /api/requirements.txt

COPY ./main.py /api
COPY ./v1 /api/v1

ENV MONGODB_URL="mongodb://192.168.1.36:27017"

EXPOSE 8080

CMD ["python3", "./main.py"]