name: Build and Push Docker images

on:
  push:
    tags:
      - '*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Builder
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push API image
        uses: docker/build-push-action@v2
        with:
          context: ./api
          push: true
          tags: ghcr.io/r-dvl/${{ github.repository }}/bandanize-api:latest

      - name: Build and push UI image
        uses: docker/build-push-action@v2
        with:
          context: ./ui
          push: true
          tags: ghcr.io/r-dvl/${{ github.repository }}/bandanize-ui:latest
